# Site
repository: muhirwan-to/muhirwan-to.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Muhammad Irwanto
title: C++ C# Programmer | Android Developer
email: muhammad.irwanto95@gmail.com
website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  muhirwan-to
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: muhammadirwanto.me
# flickr_username: jekyll
instagram_username: muhammadirwanto.me
linkedin_username: muhammad-irwanto-87bbb512a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
googleplus_username: muhi.dev
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I’m a programmer who loves to write a neat & efficient code. I was mostly working with C++ for past game development and C# .NET for mobile & web application development, also other languages such as Java, Python, ActionScript, etc. depends on the projects. I am interested to improve my experience and programming skill on C++ or Java, and especially C# .NET. But still possible to learn other programming languages.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CalCula - Daily Calculator
        link: https://play.google.com/store/apps/details?id=com.muhidev.calcula
        link_text: Google Play Application Page
        additional_links:
          - title:  Developer Page
            icon: fab play
            url: https://play.google.com/store/apps/dev?id=5945721745087054638
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I love to develop this app, it gives me a lot of knowledges to build android application from scratch.
        description: | # this will include new lines to allow paragraphs
          I am a self-learner & continuously developing my knowledges in every spare time. CalCula was developed using C# Xamarin.Android with Material Design to build it's beautiful UI. The code build in MVVM desing pattern so it's maintainable, testable, and flexible. The latest version was released on May, 13th 2023.
      - layout: top-middle
        title: Cellmatic (Automated Cell-Culture System)
        link: https://formulatrix.com/automated-cell-culture/
        link_text: Cellmatic web page
        # additional_links:
        #   - title:  Developer Page
        #     icon: fab play
        #     url: https://play.google.com/store/apps/dev?id=5945721745087054638
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          In this project, I got lot of knowledges about web API, unit testing, dependency injection, etc.
        description: | # this will include new lines to allow paragraphs
          I was working in a team which creates automation system for cell culture as backend Software Engineer. I was worked in some scopes such as infrastructure & scheduler to build a software uwing C# ASP .NET.
		  As infrastructure team, I implement unit test using xUnit to catch bugs early before deploy the code with real hardware.
		  As scheduler team, I implement error handling so the system can take a recovery action if there is an unexpected behavior.
		  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
