# Site
repository: muhirwan-to/muhirwan-to.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Muhammad Irwanto
title: C++ C# Programmer | Android Developer
email: muhammad.irwanto95@gmail.com
website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  muhirwan-to
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: muhammadirwanto.me
# flickr_username: jekyll
instagram_username: muhammadirwanto.me
linkedin_username: muhammad-irwanto-87bbb512a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username:
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a passionate programmer dedicated to crafting clean and optimized code. My experience primarily revolves around <mark>C++</mark> & <mark>Java</mark> in the realm of game development, and <mark>C#</mark> .NET for creating mobile and web applications. I am actively seeking opportunities to further enhance my expertise and programming skills, with a particular focus on advancing my proficiency in both <mark>C++</mark> and <mark>C#</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CalCula - Daily Calculator (Sept 2021 - Present)
        link: https://play.google.com/store/apps/details?id=com.muhidev.calcula
        link_text: Download on Google Play
        additional_links:
          - title:  Google Play Developer Page
            icon: fab fa-globe
            url: https://play.google.com/store/apps/dev?id=5945721745087054638
        quote: >
          I love to developing this app, as it provides me with extensive knowledge and hands-on experience in building android applications from scratch.
        description: | # this will include new lines to allow paragraphs
          CalCula was created utilizing <mark>C#</mark> <mark>Xamarin.Android</mark> in conjunction with <mark>Material Design</mark> to achieve an aesthetically pleasing user interface. The application's code follows the <mark>MVVM</mark> design pattern, ensuring its maintainability, testability, and adaptability. Additionally, several other cutting-edge technologies have been incorporated into this project, including <mark>SQLite</mark>, <mark>Live Data</mark>, <mark>Nancy</mark>, <mark>Google Play Update</mark>, <mark>Polly</mark>, and <mark>Firebase</mark>.

      - layout: top-middle
        title: Cellmatic (Automated Cell-Culture System) (Aug 2022 - Feb 2023)
        link: https://formulatrix.com/automated-cell-culture/
        link_text: Formulatrix Product - Cellmatic
        quote: >
          Through this project, I have gained extensive knowledge in various areas such as web API development, unit testing, and dependency injection.
        description: | # this will include new lines to allow paragraphs
          I was working in <mark>C#</mark> <mark>ASP .NET Core</mark> web API as backend software engineer to creates automation system for cell culture. My responsibilities encompassed two main areas: infrastructure & scheduler. On the infrastructure team, I collaborated with colleagues to **develop comprehensive unit tests** to ensure the system's reliability and quality. In my role on the scheduling team, I **implement error handling** feature.

      - layout: top-middle
        title: Minion Rush (Amazon Kindle Devices Version) (Aug 2021 - Aug 2022)
        link: https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftDMHM&hl=en&gl=US
        link_text: Minion Rush on Google Play
        quote: >
          I served as the sole programmer in this project, taking on the responsibility of handling all programmer's tasks independently.
        description: | # this will include new lines to allow paragraphs
          I am accountable for **ensuring the smooth functionality of the game on Amazon devices**, diligently assisting the producer in deploying the game seamlessly, and eliminating any critical issues that may arise.

      - layout: top-middle
        title: Sniper Fury (Gameloft Shop Version) (Nov 2020 - Aug 2021)
        link: https://www.youtube.com/watch?v=U8GvEnrTAM4
        link_text: Sniper Fury HD
        additional_links:
          - title:  Wapshop - Sniper Fury
            icon: fab fa-globe
            url: https://wapshop.gameloft.com/telkomsel/ayce/product.php?phoneId=36112&product=4211&sv=127m9mdvraedqrv0zsavptixb&c=100&crt_param=texo&texo=true&from=ADID-435645
        quote: >
          This project has afforded me valuable insights into the workings of online multiplayer and DLC systems.
        description: | # this will include new lines to allow paragraphs
          * The implementation of online multiplayer functionality is currently handled by code running on the *Game Server*. To remove this feature, I will need to **migrate certain server-side code** (developed in Python) **to the client side** (using <mark>C++</mark>).
          * **Enhance the Python-based building system** to optimize the game size in alignment with the specifications provided by the *Game Designer*. This involves revising the existing asset building mechanism to accommodate **DLC** assets.

      - layout: top-middle
        title: Real Football 2021 (Jan 2020 - Sept 2020)
        link: https://wapshop.gameloft.com/telkomsel/ayce/product.php?phoneId=36112&product=4407&sv=127m9mdvraedqrv0zsavptixb&c=100&crt_param=texo&texo=true&from=ADID-435645
        link_text: Real Football 2021 in Wapshop
        quote: >
          I acquired fresh experiences while working with the Flash IDE, an older tool that utilizes ActionScript.
        description: | # this will include new lines to allow paragraphs
          This game is an adaptation of the previous version, which required me to **upgrade the libraries to their latest version** while minimizing the risk of disrupting the game's functionality.
          * Upgrading the libraries to newer versions often introduces numerous issues. My responsibility was to **identify the most suitable version** that resulted in a minimal number of errors within the given timeframe.
          * The game's user interface underwent a significant overhaul, and the *Game Designer* required assistance from a programmer to seamlessly **integrate the UI with the game code using ActionScript**.
          * The game lacks cloud storage functionality. In this regard, I contributed to the team by **implementing Cloud Save** utilizing the company's internal library.

      - layout: top-middle
        title: Casual 3D Football Game (Not Published) (Jan 2019 - Jan 2020)
        link: 
        link_text: 
        quote: >
          This project has been one of the most amazing experiences for me as a C++ game programmer.
        description: | # this will include new lines to allow paragraphs
          This project is my favorite because it involves working on the physics behavior of the game. Our team is transforming a non-football game into a football game, and I am mainly responsible for implementing **3D collision and physics behavior** such as gravity and force. Additionally, I am also tasked with implementing the ball's AI, which relies heavily on physical and mathematical calculations. In addition to these tasks, I have also worked on the following features:
          * In battle mode, we have two balls that can collide with the goal net at different positions at the same time. To make the goal net's touched behavior more realistic, I have successfully **implemented a cloth-like body behavior** for the goal net without using animation.
          * In another mode, the user needs to hit a **breakable object**, and I have **implemented physics behavior** for this, causing the object to scatter in random directions based on the collision point.
          * I have also implemented the **ball's trajectory to move in a curved path** using mathematical calculations.

      - layout: top-middle
        title: Real Football 2019 (Jan 2017 - Jan 2018)
        link: https://wapshop.gameloft.com/telkomsel/ayce/product.php?phoneId=36112&product=3452&sv=127m9mdvraedqrv0zsavptixb&c=100&crt_param=texo&texo=true&from=ADID-435645
        link_text: Real Football 2019 in Wapshop
        quote: >
          This is my first experience working on a high-definition game in Java.
        description: | # this will include new lines to allow paragraphs
          As a programmer, I take responsibility for **handling the HVGA build to ensure a seamless release** with minimal critical bugs. I meticulously analyze and address any potential issues to guarantee a smooth user experience.

      - layout: top-middle
        title: Paradise Cruise, Rival Wheels (2017 - Jan 2018)
        link: https://www.youtube.com/watch?v=GqUdxc5EDhI
        link_text: Rival Wheels HD Android
        quote: >
          My initial project involved working with a Java-based device.
        description: | # this will include new lines to allow paragraphs
          During my involvement in the Paradise Cruise & Rival Wheels projects, I served as a Java programmer, dedicated to **resolving bugs** in these games.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PT Gameloft Indonesia
        link: https://www.gameloft.com/gameloft-studios/yogyakarta
        link_text: Gameloft Yogyakarta
        sub_title: Senior Game Programmer
        caption: September 2017 - August 2022
        quote: >
          As game programmers, we are privileged to work in a vibrant and dynamic environment that fosters creativity and excitement.
        description: | # this will include new lines to allow paragraphs
          I have been engaged in both creation and porting projects, undertaking the responsibility of **implementing features as outlined in the game design document**, as well as  **maintaining existing code and resolving bugs**. My programming expertise primarily revolves around <mark>C++</mark> (4 years) and <mark>Java</mark> (1 year) for game development. I find particular satisfaction in tasks related to **game physics and collision**, as they present exciting challenges that I enthusiastically embrace.

      - layout: left
        title: PT Promaufacture Indonesia (Formulatrix)
        link: https://formulatrix.com/
        link_text: Formulatrix
        sub_title: Software Engineer (Backend)
        caption: August 2022 - February 2023
        quote: >
          Engaging in software development has been a transformative journey, enlightening me with a wealth of new knowledge and insights.
        description: | # this will include new lines to allow paragraphs
          I was working in <mark>C#</mark> <mark>ASP .NET Core</mark> web API as backend software engineer to creates automation system for cell culture. My responsibilities encompassed two main areas: infrastructure & scheduler. On the infrastructure team, I collaborated with colleagues to **develop comprehensive unit tests** to ensure the system's reliability and quality. In my role on the scheduling team, I **implement error handling** feature.

      - layout: left
        title: Personal Project & Freelancing
        link: 
        link_text: 
        sub_title: Android Developer
        caption: September 2021 - Present
        quote: >
          I am deeply passionate about programming and possess a strong interest in crafting innovative Android applications.
        description: | # this will include new lines to allow paragraphs
          I am a dedicated self-learner, constantly striving to expand my knowledge during every available opportunity. At present, I am actively engaged in developing an android application using <mark>C#</mark> <mark>Xamarin</mark>, along with <mark>Material3 design</mark>, and following the <mark>MVVM</mark> design pattern. I take pride in having successfully published two apps on the [**Google Play Store**](https://play.google.com/store/apps/dev?id=5945721745087054638), and **I look forward to continuing my efforts in creating high-quality applications** that exceed user expectations.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Diponegoro University
        caption: 2013 - 2017
        sub_title: SSi Bachelor of Science
        quote: >
          I successfully completed my Bachelor's degree in Physics, achieving an impressive GPA of 3.73 out of 4.00.
        description: | # this will include new lines to allow paragraphs
          During my academic journey, I actively engaged with a student organization to growth my soft skills and participate in numerous scientific competitions. Among my accomplishments, I take great pride in securing the esteemed position of **national 2nd place winner** in a highly competitive scientific writing competition.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mobile and software development some of my other interests and hobbies are:
      - Ride a bicycle
      - Swimming
      - Badminton
      - Chess

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
